version: "3.9"
services:
  auth-service:
    build: backend/auth-service
    ports:
      - "3001:3000"

  chat-service:
    build: backend/chat-service
    ports:
      - "3002:3000"

  web-sockets-service:
    build: backend/web-sockets-service
    ports:
      - "3003:3000"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"